### ISSUE TITLE
Some Data to test the app

### ISSUE THREAD

**Issue by fjerbi** [GGO-web/Camping-App#15]
Hello, can you drop some data to test the app? the data you used in the Firebase.

**Comment by GGO-web** [comment]
Hi, now I am using firebase just for registration, to test the app, you need to know all the secret keys which are used in ".env" file on the local machine. Here is the structure of this file (located in the project root):

REACT_APP_FIREBASE_API_KEY=YOUR_FIREBASE_KEY
REACT_APP_FIREBASE_APP_ID=YOUR_FIREBASE_APP_ID
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=YOUR_FIREBASE_MESSAGING_SENDER_ID
REACT_APP_GOOGLE_WEBCLIENT_ID=YOUR_GOOGLE_WEBCLIENT_ID.apps.googleusercontent.com.apps.googleusercontent.com
REACT_APP_CLIENT_ID=REACT_APP_GOOGLE_WEBCLIENT_ID (IDK why :) )
REACT_APP_CAMPING_API_KEY=YOUR_CAMPING_API_KEY
REACT_APP_CAMPING_BASE_URL=https://developer.nps.gov/api/v1/campgrounds

Testing camping API documentation here: https://www.nps.gov/subjects/developer/api-documentation.htm

To run a project, you need first install Node.js. Then:

1. clone the project or download the sources
2. run `npm install` to install dependencies
3. run `npm start` to run a local server
4. install Expo Go on your device
5. insert this dev server link into the corresponding field
