### ISSUE TITLE
About backend services

### ISSUE THREAD

**Issue by ergulemre** [GGO-web/Camping-App#18]
Hi brother,

I saw this project and this is looking interesting. I tested to run this app on my emulator. However I need to know your backend apis. For example when I search location, it returns anything because I do not have any backend apis. Can you share or tell your apis?

Kind regards

<img width="360" alt="Ekran Resmi 2023-01-08 23 33 09" src="https://user-images.githubusercontent.com/37808317/211217742-f4be79b2-f98a-4cf9-805b-65e5c55a64c7.png">

**Comment by GGO-web** [comment]
Hello, I put some info about .env and also about the backend for the camping locations in [issue #15 ](https://github.com/GGO-web/Camping-App/issues/15). You can try that. Also, you can try to run an Android emulator with the .apk link, which is mentioned on the homepage of the project.
